// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Chnage14040602 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chnage14040602));
        
        string IMigrationMetadata.Id
        {
            get { return "202508241019241_Chnage14040602"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
