// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _1404072101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1404072101));
        
        string IMigrationMetadata.Id
        {
            get { return "202510131534101_14040721-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
