// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class PlanServiceConfig01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlanServiceConfig01));
        
        string IMigrationMetadata.Id
        {
            get { return "202510020921563_PlanServiceConfig01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
