// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Fix_Money_Fields_To_Decimal18_0_IRR : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_Money_Fields_To_Decimal18_0_IRR));
        
        string IMigrationMetadata.Id
        {
            get { return "202510241551586_Fix_Money_Fields_To_Decimal18_0_IRR"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
