// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Revert_Patient_ApplicationUserId_To_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Revert_Patient_ApplicationUserId_To_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "202601021635448_Revert_Patient_ApplicationUserId_To_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
