// <auto-generated />
namespace ClinicApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class editPricetype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editPricetype));
        
        string IMigrationMetadata.Id
        {
            get { return "202601081230295_editPricetype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
